import React from "react";

const RecommendationCard = ({
  recommendations = []
}) => {

  return (
    <div className="recommendation-card">

      <div className="recommendation-header">

        <div className="recommendation-icon">
          🤖
        </div>

        <div>

          <h2>
            AI Risk Recommendations
          </h2>

          <p>
            Recommendations generated by
            the Site Risk Agent
          </p>

        </div>

      </div>


      {recommendations.length > 0 ? (

        <div className="recommendation-list">

          {recommendations.map(
            (recommendation, index) => (

              <div
                className="recommendation-item"
                key={index}
              >

                <div className="recommendation-number">
                  {index + 1}
                </div>


                <div className="recommendation-content">

                  <p>

                    {
                      typeof recommendation ===
                      "string"

                        ? recommendation

                        : recommendation?.message ||
                          "Safety recommendation"
                    }

                  </p>

                </div>

              </div>

            )
          )}

        </div>

      ) : (

        <div className="no-recommendations">

          <div className="safe-icon">
            ✓
          </div>

          <div>

            <h3>
              No Immediate Action Required
            </h3>

            <p>
              No additional recommendations
              have been generated.
            </p>

          </div>

        </div>

      )}


      <div className="recommendation-footer">

        <span>
          AI Analysis Status
        </span>

        <strong>
          ● Active
        </strong>

      </div>

    </div>
  );
};

export default RecommendationCard;